.alert.error
  %a.close(data-dismiss='alert') x
  %strong Une erreur s'est produite dans le rattachement des lignes au relevÃ© bancaire